### ISSUE TITLE
[S3-PBI1]Halaman profil user editable

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#10]
Sebagai User, saya ingin mengakses halaman profil, sehingga saya bisa melihat serta mengedit informasi mengenai data diri saya yang terdaftar pada website ngampus.

**Comment by achmadrafi777** [comment]
Diagram Activity
![profil](https://user-images.githubusercontent.com/92255448/171767465-c19c2fb5-f5a6-46f2-8bf4-534998163707.png)

Use Case Description
![use case edit profil](https://user-images.githubusercontent.com/92255448/171770719-ab08116d-6f22-4dcf-8ee1-8b368c644082.png)

Mockup
![Profil (1)](https://user-images.githubusercontent.com/92255448/171770203-7a5d87a8-3989-48b3-8dc0-79466c733873.png)

<img width="1920" alt="Profile (2)" src="https://user-images.githubusercontent.com/92255448/171770013-f800f324-8352-4033-b515-b0377e79cf90.png">

**Comment by praditacyn** [comment]
https://user-images.githubusercontent.com/92255448/174994934-a7030e3d-cfbc-4a73-8b1d-2c9f68dac0e9.mp4
