### ISSUE TITLE
[S3-PBI2]Halaman home admin

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#11]
Sebagai Admin, saya ingin melihat dashboard sehingga saya dapat mengetahui rangkuman data user dan informasi pada website ngampus.

**Comment by achmadrafi777** [comment]
Activity Diagram
![activity diagram 3 vpd](https://user-images.githubusercontent.com/92255448/171765693-dede5aed-8214-4241-ab6e-e9fc43239dbb.png)

Use Case Description
![home admin](https://user-images.githubusercontent.com/92255448/171770909-850fbfe8-0d9a-4a14-afa8-bfae8933ff0b.png)

Mockup
![image](https://user-images.githubusercontent.com/99406994/171785969-7dd4ec41-5a3a-41cb-8103-8d5d42a9f697.png)

**Comment by ekkynovrizalam** [comment]
ditambahkan 2-3 chart di bagian ini

**Comment by praditacyn** [comment]
https://user-images.githubusercontent.com/92255448/175001060-3e30e08b-b9f5-4f85-b8ea-ef7c4c9ff089.mp4
