### ISSUE TITLE
[S3-PBI3]Admin mengelola Approval Produk yang sudah diregistrasi oleh user

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#12]
Sebagai Admin, saya ingin mengelola approval produk, sehingga saya dapat membantu user untuk dapat mengikuti kegiatan yang disediakan oleh ngampus.

**Comment by achmadrafi777** [comment]
Activity Diagram
![approval produk](https://user-images.githubusercontent.com/92255448/171767951-4ea982c5-9def-406f-a582-380a43691710.png)

Use Case Description
![approvalall](https://user-images.githubusercontent.com/92255448/171772186-5ed20010-b0dd-43ea-b9b3-c802a60d26f4.png)

Mockup
![image](https://user-images.githubusercontent.com/81003554/164581712-08aba23c-5848-4ee0-a5b3-cc5d0804ec24.png)

**Comment by praditacyn** [comment]
https://user-images.githubusercontent.com/92255448/174999295-bfa62d63-8846-4224-a4e7-31e9cace39b5.mp4
