### ISSUE TITLE
[S3-PBI4]Halaman Home (Landing Page)

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#13]
Sebagai user saya ingin melihat halaman home ngampus yang berisikan gambaran mengenai website ini disertai about us yang berisikan info-info mengenai tim dan kontak dari ngampus.

**Comment by achmadrafi777** [comment]
Diagram Activity
![homeee](https://user-images.githubusercontent.com/92255448/171764158-c0ad7764-6f69-420a-a4b8-f0b813847755.png)
![about us dan home](https://user-images.githubusercontent.com/92255448/171763763-a8bec851-3bd0-4f44-977d-85a65b72c748.png)

Use Case Description
![homeeeeeee](https://user-images.githubusercontent.com/92255448/171771571-d76da394-7274-4335-b209-55b5ba76dae1.png)

**Comment by achmadrafirasyiddin** [comment]
![image](https://user-images.githubusercontent.com/99406994/171773727-5a495022-67e7-4b9b-85ec-0624de93075b.png)

**Comment by ekkynovrizalam** [comment]
konten bisa edit oleh admin

**Comment by praditacyn** [comment]
https://user-images.githubusercontent.com/92255448/175004049-87630975-1052-4c24-8653-88a2662d49da.mp4
