### ISSUE TITLE
[S3-PBI5]Halaman About Us

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#14]
Sebagai user saya ingin melihat halaman kegiatan, sehingga saya dapat mengakses tempat pelaksanaan dari produk yang disediakan oleh ngampus.

**Comment by achmadrafi777** [comment]
Diagram Activity
![about us](https://user-images.githubusercontent.com/92255448/171763172-b88a60b5-be91-4d91-9f13-c5a3adcb633c.png)
![about us dan home](https://user-images.githubusercontent.com/92255448/171764288-4262587f-04ce-4860-8b80-982131d7cae5.png)

Use Case Description
![about usss](https://user-images.githubusercontent.com/92255448/171771742-ac6504e9-b3a9-4545-aff3-540841767d86.png)

**Comment by achmadrafirasyiddin** [comment]
Mockup about us (User)
![image](https://user-images.githubusercontent.com/99406994/171773871-72d725c0-5bdf-4d47-bea5-a4b94ffcb82f.png)

**Comment by ekkynovrizalam** [comment]
konten harus bisa di edit

**Comment by praditacyn** [comment]
https://user-images.githubusercontent.com/92255448/174997569-fedb8650-666b-46c2-a694-d6375cdf7e52.mp4
