### ISSUE TITLE
[S1-PBI4]Halaman detail artikel jurusan dan kampus

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#4]
Sebagai user, saya ingin mengakses detail mengenai informasi jurusan dan kampus, sehingga saya dapat membaca artikel mengenai jurusan dan kampus yang disediakan oleh ngampus.

**Comment by achmadrafi777** [comment]
Mockup
![as](https://user-images.githubusercontent.com/92255448/163737463-be144827-4a83-4263-bc71-7703c9fcac7e.png)

Use case description
![u03](https://user-images.githubusercontent.com/92255448/163734252-a1bcc842-a2e3-4937-b4a2-38d324b398c1.png)

Activity Diagram
![activity diagram 8 vpd](https://user-images.githubusercontent.com/92255448/163734201-3b05aa0e-f57b-426e-8ca9-ceccc6f6aa4f.png)

**Comment by ekkynovrizalam** [comment]
harus dinamis ya kontennya. di retrieve dari DB
