### ISSUE TITLE
[S2-PBI1]Halaman Management User oleh Admin

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#5]
Sebagai Admin saya ingin mengakses halaman management user, sehingga saya dapat mengelola user yang terdaftar pada webiste ngampus.

**Comment by achmadrafi777** [comment]
Mockup
<img width="1920" alt="Admin-User (3)" src="https://user-images.githubusercontent.com/92255448/164580536-ccdb92a4-180d-4213-9017-18899ffe8204.png">

**Comment by achmadrafi777** [comment]
![image](https://user-images.githubusercontent.com/81003554/164577323-7b11e20e-ee47-4837-b382-389b5fa4b698.png)

**Comment by praditacyn** [comment]
https://user-images.githubusercontent.com/92255448/170889039-e1f08f15-395a-40d5-9bba-56573cf53f3b.mp4
