### ISSUE TITLE
[S2-PBI2]CRUD jurusan oleh admin di halaman Manage Jurusan

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#6]
Sebagai admin, saya ingin mengelola artikel jurusan pada website ngampus, sehingga user dapat melihat dan membaca artikel tersebut.

**Comment by achmadrafi777** [comment]
Mockup
<img width="1920" alt="Admin-Jurusan (1)" src="https://user-images.githubusercontent.com/92255448/164577762-036a0bff-e2a9-4d03-8c06-361b255bf018.png">

<img width="1920" alt="170878593-dc0afb6d-f4a8-4cde-8069-34c8abf4609f" src="https://user-images.githubusercontent.com/92255448/170885888-310de0c8-9209-45fa-a490-3753b8369c6f.png">

**Comment by ekkynovrizalam** [comment]
di tambahkan mockup form nya

**Comment by praditagra** [comment]
Uploading manajemen jurusan.mp4…

**Comment by praditacyn** [comment]
https://user-images.githubusercontent.com/92255448/170889833-80f6715c-9975-4327-9811-73881c57d367.mp4

**Comment by vimelya** [comment]
<img width="1920" alt="Admin-Jurusan Form" src="https://user-images.githubusercontent.com/80321560/170878593-dc0afb6d-f4a8-4cde-8069-34c8abf4609f.png">
