### ISSUE TITLE
[S2-PBI3]CRUD kampus oleh admin di halaman Manage Kampus

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#7]
Sebagai admin, saya ingin mengelola artikel kampus pada website ngampus, sehingga user dapat melihat dan membaca artikel tersebut.

**Comment by achmadrafi777** [comment]
Mockup
<img width="1920" alt="Admin-Kampus (1)" src="https://user-images.githubusercontent.com/92255448/164577477-7554b952-4008-4b90-973c-40b42d25adec.png">

**Comment by praditacyn** [comment]
https://user-images.githubusercontent.com/92255448/170889529-1d85758e-4444-49df-a77c-7ce518d0d405.mp4
