### ISSUE TITLE
[S2-PBI4]Halaman registrasi produk

### ISSUE THREAD

**Issue by achmadrafi777** [SI-RPL-2022/SI4302_G_NGAMPUS#8]
Sebagai User saya ingin melakukan registrasi produk, sehingga saya dapat melakukan mengikuti kegiatan yang disediakan oleh ngampus.

**Comment by ekkynovrizalam** [comment]
1. minta ditambahkan keterangan nama program kepo jurusan (sesuai yang diklik oleh user di halaman sebelumnya)
2. tambahkan halaman list pendaftaran kepo jurusan yang telah diajukan
3. ketika demo, wajib menampilkan transaksi yang masuk di database

**Comment by praditacyn** [comment]
https://user-images.githubusercontent.com/92255448/170869322-2097e3e3-dc92-4885-8d09-66054340c737.mp4

**Comment by vimelya** [comment]
![Form  Registrasi Produk](https://user-images.githubusercontent.com/80321560/170878660-16f214db-0f7e-4117-aabd-3add7ba363cc.png)
![Kegiatanku](https://user-images.githubusercontent.com/80321560/170878673-eeb0b030-7d4f-4938-aac6-84d0ccf3fe42.png)
